apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: skopeo copy with creds
  name: skopeo-copy-with-creds
spec:
  description: >-
    Skopeo is a command line tool for working with remote image registries.
  params:
    - default: ''
      description: URL of the image to be copied to the destination registry
      name: srcImageURL
      type: string
    - default: ''
      description: URL of the image where the image from source should be copied to
      name: destImageURL
      type: string
    - default: 'true'
      description: Verify the TLS on the src registry endpoint
      name: srcTLSverify
      type: string
    - default: 'true'
      description: Verify the TLS on the dest registry endpoint
      name: destTLSverify
      type: string
    - name: destRegcred
      type: string
      description: Secret holding the json credentials for the destination.

  steps:
    - name: create-creds-file
      image: registry.redhat.io/rhel8/skopeo@sha256:7297e3b42ef1d56a5bc1d64a979d05c157bf31b476cc526386c873a89459610a
      env:
        - name: DEST_REGCRED
          valueFrom:
            secretKeyRef:
              key: .dockerconfigjson
              name: $(params.destRegcred)
      script: >
        echo $DEST_REGCRED >> $(workspaces.source.path)/regcred.json
    - name: view-creds-file
      image: registry.redhat.io/rhel8/skopeo@sha256:7297e3b42ef1d56a5bc1d64a979d05c157bf31b476cc526386c873a89459610a
      script: >
        cat $(workspaces.source.path)/regcred.json
    - name: skopeo-copy-with-creds
      image: registry.redhat.io/rhel8/skopeo@sha256:7297e3b42ef1d56a5bc1d64a979d05c157bf31b476cc526386c873a89459610a
      script: >
        # Function to copy multiple images.

        #

        copyimages() {
          filename='$(workspaces.images-url.path)/url.txt'
          while IFS= read line || [ -n "$line" ]
          do
            cmd=""
            for url in $line
            do
              # echo $url
              cmd="$cmd \
                  $url"
            done
            skopeo copy $cmd --src-tls-verify=$(params.srcTLSverify) --dest-tls-verify=$(params.destTLSverify) --dest-authfile=$(workspaces.source.path)/regcred.json
            echo $cmd
          done < "$filename"
        }

        #

        # If single image is to be copied then, it can be passed through

        # params in the taskrun.

        if [ "$(params.srcImageURL)" != "" ] && [ "$(params.destImageURL)" != ""
        ] ; then
          skopeo copy "$(params.srcImageURL)" "$(params.destImageURL)" --src-tls-verify=$(params.srcTLSverify) --dest-tls-verify=$(params.destTLSverify) --dest-authfile=$(workspaces.source.path)/regcred.json
        else
          # If file is provided as a configmap in the workspace then multiple images can be copied.
          #
          copyimages
        fi
  workspaces:
    - name: source