apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cd-quay-event-listener
  namespace: cicd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - name: app-cd-deploy-from-image-push-taxi
    template:
      ref: app-cd-template
    bindings:
    - kind: TriggerBinding
      ref: quay-push-binding
    interceptors:
    - params:
      - name: filter
        value: $(body.updated_tags in ['latest'])
      ref:
        kind: ClusterInterceptor
        name: cel