apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
      - name: eventTypes
        value: null
      ref:
        kind: ClusterInterceptor
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'marrober/taxi-gitops')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        kind: ClusterInterceptor
        name: cel
    name: ci-dryrun-from-push
    template:
      ref: ci-dryrun-from-push-template
  - bindings:
    - kind: TriggerBinding
      ref: dev-app-taxi-taxi-binding
    - kind: TriggerBinding
      ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: webhook-secret-dev-taxi
      - name: eventTypes
        value: null
      ref:
        kind: ClusterInterceptor
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'marrober/taxi')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        kind: ClusterInterceptor
        name: cel
    name: app-ci-build-from-push-taxi
    template:
      ref: app-ci-template
status:
  configuration:
    generatedName: ""
