apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/part-of: app-taxi
  name: taxi
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/part-of: app-taxi
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/part-of: app-taxi
    spec:
      containers:
      - image: quay.io/marrober/taxi:latest
        imagePullPolicy: Always
        name: taxi
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
