apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: quay-push-binding
  namespace: cicd
spec:
  params:
  - name: quayrepositoryname
    value: $(body.name)
  - name: quayrepositoryidentifier
    value: $(body.repository)
  - name: quayurl
    value: $(body.docker_url)
  - name: tag
    value: $(body.updated_tags[0])