apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: app-cd-pipeline
  namespace: cicd
spec:
  tasks:
  - name: deploy-image
    params:
    - name: SCRIPT
      value: "oc patch deployment/taxi -n dev --patch \"{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"last-restart\":\"$(date +'%s')\"}}}}}\""
    taskRef:
      kind: ClusterTask
      name: openshift-client
