apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: quay-webhook-event-listener-route
  namespace: cicd
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-cd-quay-event-listener
    weight: 100
  wildcardPolicy: None
